# Generated by Django 4.2.6 on 2024-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
