# Generated by Django 4.2.6 on 2024-03-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenapp', '0002_alter_user_email_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
