# Generated by Django 4.2.6 on 2024-03-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenapp', '0003_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
