# Generated by Django 4.2.6 on 2023-10-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivanshapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=100)),
                ('last_name_name', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
