# Generated by Django 4.2.6 on 2023-10-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivanshapp', '0003_college_training_placement_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
