# Generated by Django 4.2.6 on 2023-10-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivanshapp', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_period',
            field=models.IntegerField(),
        ),
    ]
